---
- hosts: dev
  become: True
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: uninstall docker
      yum:
        name: docker
        state: absent
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
